Update 4!types.csv
TrainLCD/StationAPI pull request #1010
Opened 2024-09-18 06:53 UTC by mittan12

JR列車名追加

2024-09-18 17:27 UTC, TinyKitten requested changes
碌にドキュメントもないので指摘するのも申し訳ないですが確認お願いします

2024-09-18 17:27 UTC, TinyKitten commented on data/4!types.csv
> +0,154,快速,カイソク,Rapid,快车,쾌속,#DC143C,0,0,1,自動選択用,COMPLETE
kindは2(Rapid)のままで問題ないはずです

2024-09-19 02:20 UTC, mittan12 commented on data/4!types.csv
> +0,154,快速,カイソク,Rapid,快车,쾌속,#DC143C,0,0,1,自動選択用,COMPLETE
間違えて書き換えてしまってました。
75行はは書き換え前の状態にしておいてください。

2024-09-19 02:53 UTC, TinyKitten commented on data/4!types.csv
> +0,154,快速,カイソク,Rapid,快车,쾌속,#DC143C,0,0,1,自動選択用,COMPLETE
ありがとうございます
Request ChangesなのでPR出していただいている側が修正していただくのが理想ですが、特に難しい修正ではないのでこちらで対応しますね。

2024-09-19 02:53 UTC, TinyKitten approved these changes

2024-09-19 02:53 UTC, merged