データ更新
TrainLCD/StationAPI pull request #1072
Opened 2024-10-02 03:30 UTC by TinyKitten

2024-10-02 05:08 UTC, TinyKitten commented
@10mocy 軽く変更見て問題なさそうならApproveもらえると
忙しくて見れないならセルフマージするんで言ってください

2024-10-02 10:12 UTC, TinyKitten commented
@10mocy 今見てる？

2024-10-02 15:36 UTC, 10mocy requested changes

2024-10-02 15:36 UTC, 10mocy commented on data/3!stations.csv
>  2300603,2300109,青砥,アオト,Aoto,青砥,아오토,09,,,,23006,13,125-0062,東京都葛飾区青戸三丁目36番1号,139.856292,35.745883,1928-11-01,0000-00-00,0,2300603
[ask] 京成成田空港線は京成高砂〜成田空港の路線なのですが、データとしては正しいでしょうか？

2024-10-02 15:36 UTC, 10mocy commented on data/3!stations.csv
> +2300627,9934014,印西牧の原,インザイマキノハラ,Inzaimakinohara,印西牧原,인자이마키노하라,13,,,,23006,12,270-1337,千葉県印西市草深２１９１,140.166911,35.803608,0000-00-00,0000-00-00,0,2300627
[ask] ここの追加分は京成成田空港線と同一線路を共有する北総鉄道北総線の駅なのですがこのまま追加しても問題ないでしょうか？

2024-10-02 15:36 UTC, 10mocy commented on data/3!stations.csv
> +3100124,3100124,近鉄奈良,キンテツナラ,Kintetsu-Nara,近铁奈良,긴테쓰나라,28,,,,31001,29,630-8215,奈良県奈良市東向中町２９,135.827472,34.684323,0000-00-00,0000-00-00,0,3100124
- 今回追加分のデータは全て近鉄奈良線と思われるのですが、近鉄難波線が指定されているようです。
  - [fyi] 大阪難波〜近鉄奈良は[運行形態上 近鉄奈良線 として扱われる](https://ja.wikipedia.org/wiki/%E8%BF%91%E9%89%84%E5%A5%88%E8%89%AF%E7%B7%9A#%E9%A7%85%E4%B8%80%E8%A6%A7:~:text=%E9%81%8B%E8%BB%A2%E7%B3%BB%E7%B5%B1%E4%B8%8A%E3%81%AF%E9%9B%A3%E6%B3%A2%E7%B7%9A%EF%BC%88%E5%A4%A7%E9%98%AA%E9%9B%A3%E6%B3%A2%E9%A7%85%20%2D%20%E5%A4%A7%E9%98%AA%E4%B8%8A%E6%9C%AC%E7%94%BA%E9%A7%85%E9%96%93%EF%BC%89%E3%83%BB%E5%A4%A7%E9%98%AA%E7%B7%9A%EF%BC%88%E5%A4%A7%E9%98%AA%E4%B8%8A%E6%9C%AC%E7%94%BA%E9%A7%85%20%2D%20%E5%B8%83%E6%96%BD%E9%A7%85%E9%96%93%EF%BC%89%E9%96%93%E3%82%92%E5%90%AB%E3%82%81%E3%81%9F%E5%A4%A7%E9%98%AA%E9%9B%A3%E6%B3%A2%E9%A7%85%20%2D%20%E8%BF%91%E9%89%84%E5%A5%88%E8%89%AF%E9%A7%85%E9%96%93%E3%81%8C%E3%80%8C%E5%A5%88%E8%89%AF%E7%B7%9A%E3%80%8D%E3%81%A8%E3%81%97%E3%81%A6%E6%89%B1%E3%82%8F%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B%E3%80%82%E4%BB%A5%E4%B8%8B%E3%80%81%E7%89%B9%E8%A8%98%E3%81%AE%E3%81%AA%E3%81%84%E9%99%90%E3%82%8A%E9%81%8B%E8%BB%A2%E7%B3%BB%E7%B5%B1%E3%81%A8%E3%81%97%E3%81%A6%E3%81%AE%E5%A5%88%E8%89%AF%E7%B7%9A%EF%BC%88%E5%A4%A7%E9%98%AA%E9%9B%A3%E6%B3%A2%E9%A7%85%20%2D%20%E8%BF%91%E9%89%84%E5%A5%88%E8%89%AF%E9%A7%85%E9%96%93%EF%BC%89%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%E8%A8%98%E8%BF%B0%E3%81%99%E3%82%8B%E3%80%82)という記載があります。
  - [ask] 難波線: 大阪難波駅〜大阪上本町駅, 大阪線: 大阪上本町駅〜布施駅, 奈良線: 布施駅〜近鉄奈良駅と所属路線がそれぞれ分かれているのですが、データ的には問題ありませんか？

2024-10-02 15:36 UTC, 10mocy commented on data/4!types.csv
> +0,296,鎌倉,カマクラ,Kamakura,镰仓,가마쿠라,#00008b,0,4,0,,COMPLETE
- [fya] これらの種別を使用していない場合は削除してください。
- [nits] 種別データと停車駅データは一貫性を保つために同時にコミットするようにしてください。

2024-10-02 15:36 UTC, 10mocy commented on data/5!station_station_types.csv
- [ask] 埼京線, 東海道線(湘南新宿ライン), 東急東横線の情報が削除されていますが意図通りですか？

2024-10-02 15:36 UTC, 10mocy commented on data/5!station_station_types.csv
> -0,3100502,100,194,0,鶴橋
- [ask] 別路線と接続する駅の扱いに一貫性が無いように見えますが問題ありませんか？

2024-10-02 15:36 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,2300627,503,206,1,印西牧の原
- [ask] stations でのコメントに関連。以下も同様。

2024-10-02 15:36 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,3100105,318,332,1,今里
- [ask] 接続駅の一貫性について。

2024-10-02 15:36 UTC, 10mocy commented on data/5!station_station_types.csv
> -0,1134236,100,1017,0,長岡
- [ask] ここのデータの行方は？

2024-10-02 15:39 UTC, TinyKitten commented
@mittan12 上記の指摘をご確認の上ご対応していただけると幸いです

2024-10-02 23:54 UTC, mittan12 commented on data/5!station_station_types.csv
> -0,1134236,100,1017,0,長岡
このデータは重複していたので削除しました

2024-10-02 23:56 UTC, TinyKitten commented
デプロイのCIコケてますが修正中なのでこのPRとは関係ないです

2024-10-02 23:57 UTC, mittan12 commented on data/3!stations.csv
>  2300603,2300109,青砥,アオト,Aoto,青砥,아오토,09,,,,23006,13,125-0062,東京都葛飾区青戸三丁目36番1号,139.856292,35.745883,1928-11-01,0000-00-00,0,2300603
元のデータが京成上野起点になっていたのでこのようにしましたが、京成高砂起点のほうが実態に合っているように思われます。

2024-10-02 23:57 UTC, mittan12 commented on data/3!stations.csv
> +2300627,9934014,印西牧の原,インザイマキノハラ,Inzaimakinohara,印西牧原,인자이마키노하라,13,,,,23006,12,270-1337,千葉県印西市草深２１９１,140.166911,35.803608,0000-00-00,0000-00-00,0,2300627
線路を共有しているので問題ないと思います。

2024-10-03 00:17 UTC, mittan12 commented on data/3!stations.csv
> +3100124,3100124,近鉄奈良,キンテツナラ,Kintetsu-Nara,近铁奈良,긴테쓰나라,28,,,,31001,29,630-8215,奈良県奈良市東向中町２９,135.827472,34.684323,0000-00-00,0000-00-00,0,3100124
所属路線はそのようになっているようですが、運行形態上は大阪難波～近鉄奈良まで一体となっており、案内上も大阪線とは別れているので、その点については問題ないと思われますが、近鉄難波線と近鉄奈良線の扱いについて、aliasesデータおよびline_aliasesデータに追加した8番のデータで対応したつもりではありますが、問題があるようでしたら31020のデータに大阪上本町～布施間を追加の上で大阪難波～大阪上本町間を近鉄難波線、大阪上本町～近鉄奈良間を近鉄奈良線としても良いかもしれません。

2024-10-03 00:20 UTC, mittan12 commented on data/4!types.csv
> +0,296,鎌倉,カマクラ,Kamakura,镰仓,가마쿠라,#00008b,0,4,0,,COMPLETE
これらの種別に対応する停車駅データはあとで追加するつもりでした。
今後複数のデータにまたがる追加は同時にコミットするようにします。

2024-10-03 00:21 UTC, mittan12 commented on data/5!station_station_types.csv
データがほかのデータと重複していたので削除しました。

2024-10-03 00:30 UTC, TinyKitten commented on data/3!stations.csv
>  2300603,2300109,青砥,アオト,Aoto,青砥,아오토,09,,,,23006,13,125-0062,東京都葛飾区青戸三丁目36番1号,139.856292,35.745883,1928-11-01,0000-00-00,0,2300603
元のデータが誤っていることがよくあるので基本的に実態に合わせて欲しいです

2024-10-03 00:31 UTC, TinyKitten commented
@10mocy 議論が終わったらresolveしてもろて

2024-10-03 02:43 UTC, 10mocy commented on data/3!stations.csv
> +3100124,3100124,近鉄奈良,キンテツナラ,Kintetsu-Nara,近铁奈良,긴테쓰나라,28,,,,31001,29,630-8215,奈良県奈良市東向中町２９,135.827472,34.684323,0000-00-00,0000-00-00,0,3100124
@TinyKitten に別窓で確認し旅客案内上に準じる形で問題ないことを確認したため Resolved とします

2024-10-03 02:49 UTC, TinyKitten commented on data/5!station_station_types.csv
> -0,3100502,100,194,0,鶴橋
鶴橋から今里に入る時どっちもIDが31001で入ってるから同じ路線だし問題ないと思う
3100502に入る元のデータがおかしいかも

2024-10-03 02:51 UTC, TinyKitten commented on data/5!station_station_types.csv
> -0,3100502,100,194,0,鶴橋
![スクリーンショット 2024-10-03 11 50 52](https://github.com/user-attachments/assets/e61ed43b-b2ae-403c-9ae6-efc22a77f5e7)
@10mocy おかしくなさそう

2024-10-03 07:27 UTC, TinyKitten commented on data/4!types.csv
> +0,296,鎌倉,カマクラ,Kamakura,镰仓,가마쿠라,#00008b,0,4,0,,COMPLETE
@10mocy これ何待ち？

2024-10-03 07:27 UTC, TinyKitten commented on data/4!types.csv
> +0,296,鎌倉,カマクラ,Kamakura,镰仓,가마쿠라,#00008b,0,4,0,,COMPLETE
削除云々か

2024-10-04 11:35 UTC, 10mocy approved these changes
LGTM

2024-10-04 11:36 UTC, merged