特急系統追加
TrainLCD/StationAPI pull request #1079
Opened 2024-10-04 13:33 UTC by mittan12

2024-10-04 13:34 UTC, mittan12 commented on data/5!station_station_types.csv
> -0,3102528,306,377,0,近鉄奈良
377系統は321系統と重複のため削除

2024-10-05 07:28 UTC, TinyKitten commented
@10mocy 確認よろしく
時間かかりそうだったりしたら先に言ってもらえると

2024-10-08 10:40 UTC, 10mocy requested changes
@mittan12 
一旦関西エリアを確認しました。確認してほしい箇所にコメントしたので確認と修正をお願いします。
後ほど関東エリアも確認します。

2024-10-08 10:40 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,1110610,294,1043,0,富良野
- [fya] type 294 がニセコ, 295 がフラノラベンダーエクスプレスです。設定の確認をお願いします。

2024-10-08 10:40 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,1130505,296,1045,1,新秋津
- [fyi] 特急鎌倉は新秋津にも停車すると思います。

2024-10-08 10:40 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,1130810,296,1045,0,大船
- [fyi] 横浜の次の停車駅は北鎌倉だと思います。

2024-10-08 10:40 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,1161619,288,1049,0,鳥取
- [fya] 西明石, 加古川, 竹田 は一部列車の停車駅となっているようです。確認をお願いします。

2024-10-08 10:40 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,1160903,289,1050,0,網干
- [fya] らくラクはりまは 2024/3/16 から京都～網干に延長となったと思います。確認をお願いします。

2024-10-08 10:40 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,1160707,292,1053,1,法隆寺
- [fya] まほろばは法隆寺にも停車すると思います。確認をお願いします。

2024-10-08 23:57 UTC, mittan12 commented
ご指摘のあった入力ミスについては修正しました。

2024-10-10 01:55 UTC, TinyKitten commented
@10mocy 確認できたところはresolveして

2024-10-14 05:00 UTC, TinyKitten approved these changes

2024-10-14 05:00 UTC, TinyKitten commented
@10mocy ~~関東エリアって見れてる？~~
resolveされてないのがあるからそれか

2024-10-14 05:03 UTC, TinyKitten commented
@mittan12 見るのが遅くなり申し訳ないです
コンフリクト発生しているので出先から帰り次第確認します

2024-10-15 03:11 UTC, 10mocy requested changes

2024-10-15 03:11 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,2500114,526,1054,2,成城学園前
- 特急さがみは成城学園前には止まらないと思います。

2024-10-15 03:11 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,2500127,526,1054,0,町田
- 特急さがみの一部列車は町田に停車しません。

2024-10-15 03:11 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,2500134,526,1054,0,本厚木
- 特急さがみの一部列車は本厚木に停車しません。

2024-10-15 03:11 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,2500123,527,1055,1,新百合ヶ丘
- モーニングウェイの一部列車は新百合ヶ丘に停車します。

2024-10-15 03:11 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,2500127,527,1055,1,町田
- モーニングウェイの一部列車は町田に停車します。

2024-10-15 03:11 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,2300143,537,1067,0,成田空港（第１旅客ターミナル）
- シティライナーは成田空港には停車しないと思います。

2024-10-15 03:11 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,3300120,412,1074,0,枚方市
- 種別グループ 1074 は樟葉始点にしてください

2024-10-15 03:11 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,3100532,306,1075,2,榛原
- [ask] 京都～伊勢志摩間の列車で榛原に停車する便はありますか？

2024-10-15 03:11 UTC, 10mocy commented on data/5!station_station_types.csv
> +0,3100544,306,1075,2,榊原温泉口
- [ask] 京都～伊勢志摩間の列車で榊原温泉口に停車する便はありますか？

2024-10-15 09:45 UTC, 10mocy commented
@mittan12 ご修正を確認しました。
残りの箇所をご確認・ご対応いただいてもよろしいでしょうか？

2024-10-15 09:52 UTC, TinyKitten commented
@mittan12 コンフリクト発生しているので解消コミットお願いできますか？多分PR側の変更を取り込むだけだと思うので

2024-10-20 03:09 UTC, closed without merging

2024-10-20 03:17 UTC, TinyKitten commented
data/preview間違えて消してたからこっちもcloseされたのか...
@mittan12 申し訳ございませんがもう一度PRをopenしていただけると🙇

2024-10-20 03:18 UTC, TinyKitten commented
reopen

2024-10-26 10:18 UTC, mittan12 commented
再オープンしました
#1103