:zap: シェフ強制労働
TrainLCD/StationAPI pull request #634
Opened 2023-07-10 12:10 UTC by Sw-Saturn

ステージ名は微妙なのでちゃんとつけましょう

2023-07-10 12:43 UTC, TinyKitten commented
review requestってそっちからつけれるんだっけ
付けれるなら終わったらアサインしてほしいんだけど

2023-07-10 12:46 UTC, TinyKitten commented
神
一応普段gRPC対応の環境に使ってるdev版最悪動かなくても問題ないのでそこに２回程度デプロイして検証する

2023-07-10 13:10 UTC, Sw-Saturn commented
@TinyKitten 
申し訳ない
完全にソースコピーするの忘れてた

今の状態でローカルでビルド回してみてキャッシュ使えてるのは確認した
<img width="896" alt="スクリーンショット 2023-07-10 22 07 40" src="https://github.com/TrainLCD/StationAPI/assets/20313668/c36ac54f-d701-4eea-8f03-e809f889f8d7">

2023-07-10 15:37 UTC, TinyKitten commented
@Sw-Saturn １５分くらい余計遅くなってるのでここ治らんとマージできないね:cry:

2023-07-11 00:59 UTC, Sw-Saturn commented
@TinyKitten 
空き時間にビルド回してもらえると助かる（権限ないので振ってくれると嬉しいかも）

2023-07-11 01:05 UTC, TinyKitten commented
@Sw-Saturn 1回に810億円の使用料金徴収するけどIAMで設定したゾ

2023-07-11 03:23 UTC, TinyKitten commented
@Sw-Saturn 最近転んで怪我することが多いけどCIまでコケたぞ

2023-07-11 03:26 UTC, TinyKitten commented on Dockerfile
> +RUN rsync --recursive --checksum --itemize-changes --verbose original/ .
`rsync` 何に必要で使ってるの？ちょっと変更の意図がわからんのでもしDockerfileでrsyncを使うのが一般的ではないのであればコメントほしい
あと高校生の時星野先生いたけどめっちゃ優しくて良い人だった

2023-07-11 04:55 UTC, Sw-Saturn commented on Dockerfile
> +RUN rsync --recursive --checksum --itemize-changes --verbose original/ .
cargo-chefによるソースへの変更を巻き戻すことでイメージのキャッシュを再利用できるようにする目的

↓によるとrsync使うしかないっぽいような気がする
https://stackoverflow.com/questions/36553502/is-there-a-way-to-add-only-changed-files-to-a-docker-image-as-a-new-layer-with#36561768

2023-07-11 13:57 UTC, TinyKitten commented
ギフハブ見てないうちにクッソコード変わってて

2023-07-12 04:55 UTC, TinyKitten commented on Dockerfile
>  RUN SQLX_OFFLINE=true cargo build --release
[ask]
なんでcargo build2回必要なんだっけ？必要だとしても `SQLX_OFFLINE=true` がないとsqlxに怒られる気がするけどビルド通ってるしいらないのかな。
https://github.com/TrainLCD/StationAPI/pull/634/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R12

[nits]
cargo buildで標準出力使わなかったら若干速くなるのかな（別に対応しなくてもいいけど）
```suggestion
RUN SQLX_OFFLINE=true cargo build --release --quiet
```

2023-07-12 05:03 UTC, Sw-Saturn commented on Dockerfile
>  RUN SQLX_OFFLINE=true cargo build --release
IO遅いマシンで動いてるから標準出力吐かせなくするのは効果ありそうかも
見れるときに対応しまーす

2023-07-12 05:05 UTC, TinyKitten commented on Dockerfile
>  RUN SQLX_OFFLINE=true cargo build --release
[imo]
`RUN cargo build --release` は多分不要。依存関係だけキャッシュさせるという意図であっても今は依存関係がどうなるかは誰にもわからん開発が黎明期なので、一旦外して通しでどの程度キャッシュされて時間が短縮されるか測定した後適用して差分見るとかが良いと思ってます

2023-07-12 05:06 UTC, TinyKitten commented on Dockerfile
> +RUN cargo build --release
[imo]
https://github.com/TrainLCD/StationAPI/pull/634/files#r1260590638
依存関係だけキャッシュするという意図であれば今のところ足引っ張りそうだなあという印象

2023-07-12 05:08 UTC, TinyKitten commented
着実に速くなってる感じがする（なしだと20分以上は確実に取られてたけど20分切ってる:yum:）
k8s使うってことで若干料金が不安だけど慣らし運転って感じで
一旦ビルドは1回のみにしてもろて、対応後にもう一度レビューリクください

<img width="375" alt="スクリーンショット 2023-07-12 13 26 09" src="https://github.com/TrainLCD/StationAPI/assets/32848922/e9abdfc4-7476-4069-a78d-77ca1c785b48">
<img width="384" alt="スクリーンショット 2023-07-12 14 07 10" src="https://github.com/TrainLCD/StationAPI/assets/32848922/aedd818d-430c-4eb9-8b7c-713d8737f888">

2023-07-12 14:00 UTC, TinyKitten commented
@Sw-Saturn 
<img width="394" alt="スクリーンショット 2023-07-12 23 00 16" src="https://github.com/TrainLCD/StationAPI/assets/32848922/1395e1f9-0641-44cc-86a0-0089791b1a21">
![image](https://github.com/TrainLCD/StationAPI/assets/32848922/08c2a91c-7ee1-4fea-b811-60ae6a20826d)

2023-07-12 14:02 UTC, TinyKitten commented
@all-contributors please add @Sw-Saturn for infrastructure and code

2023-07-12 14:06 UTC, TinyKitten commented
作業終わったら再レビュー申請ください

2023-07-12 14:20 UTC, Sw-Saturn commented
2回目は遅くなった
![スクリーンショット 2023-07-12 23 15 30](https://github.com/TrainLCD/StationAPI/assets/20313668/0f2f1239-de41-4507-b37b-b204342d566f)

推測: 同時に2つのビルドジョブが走っていたのでパフォーマンス落ちた?

単体でもう一回走らせて確認する

2023-07-12 14:59 UTC, TinyKitten commented on Dockerfile
> +COPY build.rs .
別に何でもいいけどこれは空っぽのmain関数じゃなくていいの？

2023-07-12 15:15 UTC, Sw-Saturn commented on Dockerfile
> +COPY build.rs .
こっちも空にしておくべきだね
Cloud Buildの構成の指定がインラインになっていたので [1415584](https://github.com/TrainLCD/StationAPI/pull/634/commits/141558440fe7648cab9e7239569e2bc9522d1b25) の変更は一旦リバーと

2023-07-12 15:35 UTC, TinyKitten commented
`cloudbuild.yaml` いいやつだったよ...

2023-07-12 16:19 UTC, Sw-Saturn commented
イメージの全てのレイヤーのキャッシュが使えた場合2分半で終わった
![スクリーンショット 2023-07-13 1 19 07](https://github.com/TrainLCD/StationAPI/assets/20313668/6984ffe0-019f-4aad-85ca-8d80bbee8946)

2023-07-12 16:21 UTC, TinyKitten approved these changes
アホおもろいやん

2023-07-12 16:21 UTC, Sw-Saturn commented
草

2023-07-12 16:23 UTC, TinyKitten requested changes
そり、なんかURLにアクセスすると空っぽのファイルが落ちてくるのでビルドできてなさそうかも

2023-07-12 16:25 UTC, TinyKitten approved these changes
や、寝ぼけてた
Postmanでは生きてる
<img width="1582" alt="スクリーンショット 2023-07-13 1 24 39" src="https://github.com/TrainLCD/StationAPI/assets/32848922/30679de7-5316-4abd-8ec6-028b0568c8cb">
卍しまーす

2023-07-12 16:26 UTC, merged